//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredientes()
        {
            this.PlatoIngrediente = new HashSet<PlatoIngrediente>();
        }
    
        public int IdIngrediente { get; set; }
        public string Ingrediente { get; set; }
        public string Descripcion { get; set; }
        public string Url_Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatoIngrediente> PlatoIngrediente { get; set; }
    }
}
