//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatoEtiqueta
    {
        public int IdPlatoEtiqueta { get; set; }
        public int IdPlato { get; set; }
        public int IdEtiqueta { get; set; }
    
        public virtual Etiquetas Etiquetas { get; set; }
        public virtual Platos Platos { get; set; }
    }
}
