//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Restaurantes : DbContext
    {
        public Restaurantes()
            : base("name=Restaurantes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Etiquetas> Etiquetas { get; set; }
        public virtual DbSet<Ingredientes> Ingredientes { get; set; }
        public virtual DbSet<Medidas> Medidas { get; set; }
        public virtual DbSet<PlatoEtiqueta> PlatoEtiqueta { get; set; }
        public virtual DbSet<PlatoIngrediente> PlatoIngrediente { get; set; }
        public virtual DbSet<Platos> Platos { get; set; }
    }
}
